// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PutRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutRequest) Reset()         { *m = PutRequest{} }
func (m *PutRequest) String() string { return proto.CompactTextString(m) }
func (*PutRequest) ProtoMessage()    {}
func (*PutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *PutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutRequest.Unmarshal(m, b)
}
func (m *PutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutRequest.Marshal(b, m, deterministic)
}
func (m *PutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutRequest.Merge(m, src)
}
func (m *PutRequest) XXX_Size() int {
	return xxx_messageInfo_PutRequest.Size(m)
}
func (m *PutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutRequest proto.InternalMessageInfo

func (m *PutRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *PutRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type GetAndDeleteRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAndDeleteRequest) Reset()         { *m = GetAndDeleteRequest{} }
func (m *GetAndDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*GetAndDeleteRequest) ProtoMessage()    {}
func (*GetAndDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *GetAndDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAndDeleteRequest.Unmarshal(m, b)
}
func (m *GetAndDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAndDeleteRequest.Marshal(b, m, deterministic)
}
func (m *GetAndDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAndDeleteRequest.Merge(m, src)
}
func (m *GetAndDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_GetAndDeleteRequest.Size(m)
}
func (m *GetAndDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAndDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAndDeleteRequest proto.InternalMessageInfo

func (m *GetAndDeleteRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type Response struct {
	ResponseCode         int32    `protobuf:"varint,1,opt,name=responseCode,proto3" json:"responseCode,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetResponseCode() int32 {
	if m != nil {
		return m.ResponseCode
	}
	return 0
}

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*PutRequest)(nil), "proto.PutRequest")
	proto.RegisterType((*GetAndDeleteRequest)(nil), "proto.GetAndDeleteRequest")
	proto.RegisterType((*Response)(nil), "proto.Response")
}

func init() {
	proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626)
}

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 222 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x26, 0x5c,
	0x5c, 0x01, 0xa5, 0x25, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42, 0x02, 0x5c, 0xcc, 0xd9,
	0xa9, 0x95, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x20, 0xa6, 0x90, 0x08, 0x17, 0x6b, 0x59,
	0x62, 0x4e, 0x69, 0xaa, 0x04, 0x13, 0x58, 0x0c, 0xc2, 0x51, 0x52, 0xe7, 0x12, 0x76, 0x4f, 0x2d,
	0x71, 0xcc, 0x4b, 0x71, 0x49, 0xcd, 0x49, 0x2d, 0x49, 0xc5, 0xa9, 0x5d, 0xc9, 0x83, 0x8b, 0x23,
	0x28, 0xb5, 0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x55, 0x48, 0x89, 0x8b, 0xa7, 0x08, 0xca, 0x76, 0xce,
	0x4f, 0x49, 0x05, 0x2b, 0x63, 0x0d, 0x42, 0x11, 0x13, 0x92, 0xe0, 0x62, 0xcf, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x87, 0x59, 0x08, 0xe3, 0x1a, 0x6d, 0x62, 0xe4, 0x12, 0xf1, 0x4e, 0xad, 0x0c, 0x03,
	0xd9, 0x1f, 0x5c, 0x92, 0x5f, 0x94, 0x1a, 0x0c, 0xf1, 0x8e, 0x90, 0x36, 0x17, 0x73, 0x40, 0x68,
	0x88, 0x90, 0x20, 0xc4, 0x5f, 0x7a, 0x08, 0xdf, 0x48, 0xf1, 0x43, 0x85, 0x60, 0x2e, 0x50, 0x62,
	0x10, 0x32, 0xe1, 0x62, 0x76, 0x77, 0x0d, 0x11, 0x92, 0x82, 0xca, 0x60, 0xf1, 0x04, 0x36, 0x5d,
	0xe6, 0x5c, 0x6c, 0x2e, 0xae, 0x3e, 0xae, 0x21, 0xae, 0x24, 0x6a, 0x4c, 0x62, 0x03, 0x8b, 0x18,
	0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x6c, 0xdb, 0x7f, 0x10, 0x7c, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// KeyValueStoreServiceClient is the client API for KeyValueStoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type KeyValueStoreServiceClient interface {
	PUT(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*Response, error)
	GET(ctx context.Context, in *GetAndDeleteRequest, opts ...grpc.CallOption) (*Response, error)
	DELETE(ctx context.Context, in *GetAndDeleteRequest, opts ...grpc.CallOption) (*Response, error)
}

type keyValueStoreServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKeyValueStoreServiceClient(cc grpc.ClientConnInterface) KeyValueStoreServiceClient {
	return &keyValueStoreServiceClient{cc}
}

func (c *keyValueStoreServiceClient) PUT(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.KeyValueStoreService/PUT", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyValueStoreServiceClient) GET(ctx context.Context, in *GetAndDeleteRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.KeyValueStoreService/GET", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyValueStoreServiceClient) DELETE(ctx context.Context, in *GetAndDeleteRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.KeyValueStoreService/DELETE", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KeyValueStoreServiceServer is the server API for KeyValueStoreService service.
type KeyValueStoreServiceServer interface {
	PUT(context.Context, *PutRequest) (*Response, error)
	GET(context.Context, *GetAndDeleteRequest) (*Response, error)
	DELETE(context.Context, *GetAndDeleteRequest) (*Response, error)
}

// UnimplementedKeyValueStoreServiceServer can be embedded to have forward compatible implementations.
type UnimplementedKeyValueStoreServiceServer struct {
}

func (*UnimplementedKeyValueStoreServiceServer) PUT(ctx context.Context, req *PutRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PUT not implemented")
}
func (*UnimplementedKeyValueStoreServiceServer) GET(ctx context.Context, req *GetAndDeleteRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GET not implemented")
}
func (*UnimplementedKeyValueStoreServiceServer) DELETE(ctx context.Context, req *GetAndDeleteRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DELETE not implemented")
}

func RegisterKeyValueStoreServiceServer(s *grpc.Server, srv KeyValueStoreServiceServer) {
	s.RegisterService(&_KeyValueStoreService_serviceDesc, srv)
}

func _KeyValueStoreService_PUT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyValueStoreServiceServer).PUT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.KeyValueStoreService/PUT",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyValueStoreServiceServer).PUT(ctx, req.(*PutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyValueStoreService_GET_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAndDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyValueStoreServiceServer).GET(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.KeyValueStoreService/GET",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyValueStoreServiceServer).GET(ctx, req.(*GetAndDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyValueStoreService_DELETE_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAndDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyValueStoreServiceServer).DELETE(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.KeyValueStoreService/DELETE",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyValueStoreServiceServer).DELETE(ctx, req.(*GetAndDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _KeyValueStoreService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.KeyValueStoreService",
	HandlerType: (*KeyValueStoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PUT",
			Handler:    _KeyValueStoreService_PUT_Handler,
		},
		{
			MethodName: "GET",
			Handler:    _KeyValueStoreService_GET_Handler,
		},
		{
			MethodName: "DELETE",
			Handler:    _KeyValueStoreService_DELETE_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
